version: '3.8'
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

services:
  derby:
    image: opavlova/db-derby
    ports:
      - "1527:1527"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8081:80"
    networks:
      - postgres
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"